set(SPEEX_ROOT ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET})

find_path(SPEEX_INCLUDE_DIRS "speex/speex.h")
find_library(SPEEX_LIBRARY_RELEASE speex PATHS ${SPEEX_ROOT}/lib NO_DEFAULT_PATH)
find_library(SPEEX_LIBRARY_DEBUG speex PATHS ${SPEEX_ROOT}/debug/lib NO_DEFAULT_PATH)

set(SPEEX_LIBS $<IF:$<CONFIG:Debug>,${SPEEX_LIBRARY_DEBUG},${SPEEX_LIBRARY_RELEASE}>)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Speex DEFAULT_MSG SPEEX_LIBRARY_RELEASE SPEEX_LIBRARY_DEBUG SPEEX_INCLUDE_DIRS)
mark_as_advanced(SPEEX_LIBRARY_RELEASE SPEEX_LIBRARY_DEBUG SPEEX_INCLUDE_DIRS)

if(NOT TARGET speex::speex)
	add_library(speex::speex INTERFACE IMPORTED)
	set_property(TARGET speex::speex PROPERTY INTERFACE_LINK_LIBRARIES "${SPEEX_LIBS}")
	set_property(TARGET speex::speex PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${SPEEX_INCLUDE_DIRS}")
endif()
